### ISSUE TITLE
Tashkeela

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#10]
# Task
Upload HPLT into Tashkeela (asas-ai/Joud) into correct format. 

# Dataset summary:

..

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] split the dataset into train [%99] & val [1%] Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [ ] Test the dataset using ds_dataloader.py
- [ ] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [ ] Upload the dataset into hf.
