### ISSUE TITLE
Abu El-khair corpus v2

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#11]
# Task
Crawled new version of  Abu El-khair corpus into HF (asas-ai/Joud)

# News Website to be Crawling

| Source  | From | To | Website | Done |
| ------------- | ------------- |  ------------- | ------------- | ------------- |
| Alittihad  | July 2015  | Now  | [URL](https://www.aletihad.ae/)  | Not Yet  |
| Echorouk Online  | June 2015  | Now  | URL  | Not Yet  |
| Alriyadh  | Jan 2014  | Now  | URL  | Done  |
| Alyaum Online  | Jan 2014  | Now  | URL  | Done  |
| Tishreen  | June 2014  | Now  | URL  | Not Yet  |
| Alqabas   | May 2014  | Now  | URL  | Not Yet  |
| Almustaqbal   | May 2014  | Now  | URL  | Not Yet  |
| Almasry-alyoum  | July 2014  | Now  | URL  | Not Yet  |
| youm7  | June 2013  | Now  | URL  | Not Yet  |
| Saba News Agency  | June 2014  | Now  | URL  | Not Yet  |

# Steps:
- [ ] Crawling News Website.
- [ ] Use serlization.py ( load and generate json file).
- [ ] split the dataset into train [%99] & val [ 1%]. Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [ ] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [ ] compress all the files using gzip. 
- [ ] Test the dataset using ds_dataloader.py.
- [ ] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe).
- [ ] upload and integrate the dataset into (asas-ai/Joud).
