### ISSUE TITLE
CC-100

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#12]
# Task

Upload CC-100 - version into HF (asas-ai/Joud). The link of the dataset is [here](https://data.statmt.org/cc-100/)

# Dataset summary:

This corpus is an attempt to recreate the dataset used for training [XLM-R](https://www.aclweb.org/anthology/2020.acl-main.747.pdf). This corpus comprises of monolingual data for 100+ languages and also includes data for romanized languages (indicated by *_rom). This was constructed using the urls and paragraph indices provided by the [CC-Net repository](https://github.com/facebookresearch/cc_net) by processing January-December 2018 Commoncrawl snapshots. Each file comprises of documents separated by double-newlines and paragraphs within the same document separated by a newline. The data is generated using the open source CC-Net repository. No claims of intellectual property are made on the work of preparation of the corpus.

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] Divided the json into n files where each one at most 1 GB. Check [split_json.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [num_tokens.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/num_tokens.py)  
- [X] Upload the dataset into hf.
