### ISSUE TITLE
update wikipidia-dump

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#13]
# Task

Update Wikipidia-dump (20231101) into HF (asas-ai/Joud)

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe).
- [X] Upload the dataset into hf.
