### ISSUE TITLE
clips/mqa

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#14]
# Task

Upload clips/mqa - into HF (asas-ai/Joud). The link of the dataset is [here](clips/mqa)

# Dataset summary:

MQA is a Multilingual corpus of Questions and Answers (MQA) parsed from the [Common Crawl](https://commoncrawl.org/). Questions are divided in two types: Frequently Asked Questions (FAQ) and Community Question Answering (CQA).

# Steps:
- [ ] Use serlization.py ( load and generate json file)
- [ ] Divided the training into n files where each one at most 1 GB. Check [split_json.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [ ] Compress all the files using gzip.
- [ ] Test the dataset using ds_dataloader.py
- [ ] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [ ] Upload the dataset into hf.
