### ISSUE TITLE
opus

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#15]
# Task

Upload opus - into HF (asas-ai/Joud). The link of the dataset is [here](opus)

# Dataset summary:

OPUS is a growing collection of translated texts from the web. In the OPUS project we try to convert and align free online data, to add linguistic annotation, and to provide the community with a publicly available parallel corpus. OPUS is based on open source products and the corpus is also delivered as an open content package. We used several tools to compile the current collection. All pre-processing is done automatically. No manual corrections have been carried out. We collected only Arabic text here. 

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [ ] Upload the dataset into hf.
