### ISSUE TITLE
fix GeoWAC

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#16]
# Task
fix GeoWAC and integrate the dataset into HF (asas-ai/Joud).

# Problem

The files does not contain "text" field. 

# Dataset Summary

The GeoWAC corpus is created for 50 different language varieties, with a specific focus on achieving balance in terms of geographic and demographic representation.

# Steps:
- [X] Use serlization.py ( load and generate json file).
- [X] split the dataset into train [%99] & val [ 1%] Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] compress all the files using gzip. 
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe).
- [X] Upload the dataset into (asas-ai/Joud)
