### ISSUE TITLE
APD

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#17]
# Task

Upload APD - into HF (asas-ai/Joud). The link of the dataset is [here](https://data.mendeley.com/datasets/2pkxckwgs3/1)

# Dataset summary:

Arabic Punctuation Dataset (APD) is a large of annotated corpus of Arabic text with punctuation.

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [X] Upload the dataset into hf.
