### ISSUE TITLE
UNPC

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#7]
# Task

Upload UNPC into HF (asas-ai/Joud). The link of the dataset is [here](https://huggingface.co/datasets/un_pc)

# Dataset summary:

This parallel corpus consists of manually translated UN documents from the last 25 years (1990 to 2014)
for the six official UN languages, Arabic, Chinese, English, French, Russian, and Spanish. 6 languages, 15 bitexts.

# Steps:
- [x] Use serlization.py ( load and generate json file)
- [x] split the dataset into train [%99] & val [1%] Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [x] Divided the training into n files where each one at most 1 GB. Check [split_json.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [x] Compress all the files using gzip.
- [x] Test the dataset using ds_dataloader.py
- [x] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [run_num_token.sh](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/run_token_num.sh)  
- [x] Upload the dataset into hf.

**Comment by KhalidAlt** [comment]
Hi @SaiedAlshahrani lets take only the arabic text for now and ignore the English one. What do you think ?

**Comment by KhalidAlt** [comment]
Hi @SaiedAlshahrani, I re-upload the dataset with only Arabic.
