### ISSUE TITLE
HPLT

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#8]
# Task
Upload HPLT into HF (asas-ai/Joud) into correct format. 

# Dataset summary:

The HPLT project's initial release includes a vast collection of both monolingual texts and parallel texts (bitexts) that were sourced and compiled from web archives and crawls, encompassing a total of 1.7 petabytes of data. This collection spans 75 languages and comprises approximately 21.7 trillion word tokens based on whitespace tokens. 

# Steps:
- [X] Use serlization.py ( load and generate json file)
- [X] split the dataset into train [%99] & val [1%] Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [X] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [X] Compress all the files using gzip.
- [X] Test the dataset using ds_dataloader.py
- [X] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [x] Upload the dataset into hf.
