### ISSUE TITLE
MADLAD-400

### ISSUE THREAD

**Issue by KhalidAlt** [asas-lab/Joud#9]
# Task

Upload MADLAD-400 - clean version into HF (asas-ai/Joud). The link of the dataset is [here](allenai/MADLAD-400)

# Dataset summary:

MADLAD-400, standing for Multilingual Audited Dataset: Low-resource And Document-level, is a diverse, document-level multilingual dataset derived from Common Crawl, encompassing a total of 419 languages. It incorporates all available snapshots of CommonCrawl as of August 1, 2022. Its key strengths compared to similar datasets include its extensive multilingual coverage (419 languages), thorough auditing, high-level filtering, and document-level granularity. However, its extensive filtering, while a strength, could also be a drawback as it might reduce the dataset's comprehensiveness for certain uses.

The dataset is available in two variants: the 'noisy' version, which undergoes minimal filtering, only applying document-level language identification (LangID), and the 'clean' version, which is subjected to a range of filters. Despite the filtering, the clean version still retains a notable level of noise. Both versions are presented in a deduplicated, document-level format.

# Steps:
- [ ] Use serlization.py ( load and generate json file)
- [ ] split the dataset into train [%99] & val [1%] Check [generate_val.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/generate_val.py).
- [ ] Divided the training into n files where each one at most 1 GB. Check [split_json.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/split_json.sh).
- [ ] Compress all the files using gzip.
- [ ] Test the dataset using ds_dataloader.py
- [ ] Calculate the number of tokens using this tokenizer [here](https://huggingface.co/khalidalt/tokenizer_bpe). Here is a script to count the number of tokens: [token_num.py](https://github.com/asas-lab/Joud/blob/main/integrate_dataset/token_num.py)  
- [ ] Upload the dataset into hf.
